### ISSUE TITLE
Master build fails with error code 127 on npm install step.

### ISSUE THREAD

**Issue by edglazer** [cdgraff/docker-streammachine#1]
Looking to checkout Stream Machine as a viable successor to our icecast setup, and this docker looks like just the ticket to try it out. I'm having problem on step 9 of building streammachine-master, which throws this error:

ERROR: Service 'streammachine-master' failed to build: The command '/bin/sh -c cd /srv/StreamMachine; npm install' returned a non-zero code: 127

After some searching, I found a [stackoverflow](http://stackoverflow.com/questions/31876031/the-command-bin-sh-c-returned-a-non-zero-code-127) that suggests "Exit code 127 from shell commands means 'command not found'. So, in your case it seems the [binary] is not being found when Docker runs it." They're talking about 'wget' in that SO question, but my guess is that the shell isn't finding npm in this case? 

I'm running this on the Mac Docker Beta 1.12.2-rc1-beta27 (build: 12496) on El Cap 10.11.6 if that matters.  Any help is greatly appreciated!

**Comment by edglazer** [comment]
Hey, not sure if you saw this, but I would love to check out stream machine using a docker container rather than installing the full deal. Any thoughts?

**Comment by chmaynard** [comment]
@edglazer Looks like this project has been languishing for a while. Did you ever get docker-streammachine working?

**Comment by cdgraff** [comment]
@chmaynard official Branch of StreamMachine now support Docker build, take a look here:
https://github.com/StreamMachine/StreamMachine

**Comment by chmaynard** [comment]
@cdgraff Thanks! 
I have a few concerns about the official repo:
- Looks like the latest commit to the main branch failed a test.
- The maintainer did not add any images to DockerHub.
- I tried running docker-compose and was not completely successful.

**Comment by edglazer** [comment]
I never got StreamMachine running in Docker, but if the official branch supports Docker, let's close this out and they can deal with support through the official repo ticketing system.
